name: pub_mediator
version: 1.0.1
description: Diagnoses version conflicts between dependencies in Dart packages.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/pub_mediator
environment:
  sdk: ">=1.19.0"
dependencies:
  args: ^0.13.4
  cli_util: ^0.1.1
  console: ^2.0.0
  http: ^0.11.3
  pub_client: ^1.0.0
  pub_semver: ^1.0.0
  pubspec: ^0.0.14
dev_dependencies:
  test: ^0.12.0
executables:
  mediator: main
